# Generated by Django 3.1.5 on 2022-01-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20220114_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
