# Generated by Django 3.1.5 on 2022-01-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='pet',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
            preserve_default='False',
        ),
    ]
